/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tgl02_07_26;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LAB-SI-PC
 */
public class FormMahasiswa extends javax.swing.JFrame {
    MahasiswaNilai mahasiswa = new MahasiswaNilai();
    MahasiswaNilaiController controller;
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
        controller = new MahasiswaNilaiController();
        tampilData();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNilaiTugas = new javax.swing.JTextField();
        txtNilaiUas = new javax.swing.JTextField();
        txtNilaiUts = new javax.swing.JTextField();
        txtNilaiAngka = new javax.swing.JTextField();
        txtNilaiHuruf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnProses = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 18, 70, 31);

        jLabel2.setText("NIM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 55, 70, 31);

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 92, 70, 31);

        jLabel4.setText("Nilai Tugas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(24, 129, 70, 31);

        jLabel5.setText("Nilai Uas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(24, 166, 70, 31);

        jLabel6.setText("Nilai Uts");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(24, 203, 70, 31);

        jLabel7.setText("Nilai Angka");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 10, 70, 31);

        jLabel8.setText("Nilai Huruf");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 60, 70, 31);

        txtNama.setText("jTextField10");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(100, 22, 450, 22);

        txtNim.setText("jTextField11");
        getContentPane().add(txtNim);
        txtNim.setBounds(100, 59, 450, 22);

        txtAlamat.setText("jTextField12");
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(100, 96, 450, 22);

        txtNilaiTugas.setText("jTextField13");
        getContentPane().add(txtNilaiTugas);
        txtNilaiTugas.setBounds(100, 133, 450, 22);

        txtNilaiUas.setText("jTextField14");
        getContentPane().add(txtNilaiUas);
        txtNilaiUas.setBounds(100, 170, 450, 22);

        txtNilaiUts.setText("jTextField15");
        getContentPane().add(txtNilaiUts);
        txtNilaiUts.setBounds(100, 207, 450, 22);

        txtNilaiAngka.setText("jTextField16");
        getContentPane().add(txtNilaiAngka);
        txtNilaiAngka.setBounds(640, 20, 450, 22);

        txtNilaiHuruf.setText("jTextField17");
        getContentPane().add(txtNilaiHuruf);
        txtNilaiHuruf.setBounds(640, 60, 450, 22);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jPanel1.add(btnProses);
        btnProses.setBounds(7, 7, 80, 23);

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(90, 7, 81, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(24, 240, 180, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Alamat", "Nilai Tugas ", "Nilai UAS", "Nilai UTS", "Nilai Angka", "Nilai Huruf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 300, 1070, 402);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(15, 6, 80, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(580, 90, 110, 40);

        setSize(new java.awt.Dimension(1121, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        mahasiswa.setNim(txtNim.getText());
        mahasiswa.setNama(txtNama.getText());
        mahasiswa.setAlamat(txtAlamat.getText());
        mahasiswa.setTugas(Double.valueOf(txtNilaiTugas.getText()));
        mahasiswa.setUts(Double.valueOf(txtNilaiUts.getText()));
        mahasiswa.setUas(Double.valueOf(txtNilaiUas.getText()));
        txtNilaiAngka.setText(String.valueOf(mahasiswa.getNilaiAngka()));
        txtNilaiHuruf.setText(mahasiswa.getNilaiHuruf());
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clear(); 
    }//GEN-LAST:event_btnclearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MahasiswaNilai mhs = new MahasiswaNilai();
        mhs.setNim(txtNim.getText());
        mhs.setNama(txtNama.getText());
        mhs.setAlamat(txtAlamat.getText());
        mhs.setTugas(Double.parseDouble(txtNilaiTugas.getText()));
        mhs.setUts(Double.parseDouble(txtNilaiUts.getText()));
        mhs.setUas(Double.parseDouble(txtNilaiUas.getText()));
        String pesan = controller.insert(mhs);
        JOptionPane.showMessageDialog(this, pesan);
        tampilData();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiAngka;
    private javax.swing.JTextField txtNilaiHuruf;
    private javax.swing.JTextField txtNilaiTugas;
    private javax.swing.JTextField txtNilaiUas;
    private javax.swing.JTextField txtNilaiUts;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtNim.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNilaiTugas.setText("");
        txtNilaiUts.setText("");
        txtNilaiUas.setText("");
        txtNilaiHuruf.setText("");
        txtNilaiAngka.setText("");
    }
    
    public void tampilData(){
        MahasiswaNilai[] data = controller.getAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (MahasiswaNilai mhs : data) {
            Object[] row = {
                mhs.getNim(),
                mhs.getNama(),
                mhs.getTugas(),
                mhs.getUts(),
                mhs.getUas(),
                mhs.getNilaiAngka(),
                mhs.getNilaiHuruf(),
            };
            model.addRow(row);
        }
    
    }
    
    
}